//LEVEL
export const NULL_LEVEL = "NULL_LEVEL";
export const ADD_SQUARE = "ADD_SQUARE";
export const UPDATE_ISYOU = "UPDATE_ISYOU";
export const UPDATE_ISENEMY = "UPDATE_ISENEMY";
export const UPDATE_VALUE = "UPDATE_VALUE";
export const UPDATE_ISPROJECTILE = "UPDATE_ISPROJECTILE";
export const UPDATE_SPRITE = "UPDATE_SPRITE";
//LEVEL ID
export const LEVELID_UP = "LEVELID_UP";
//GAME
export const CHANGE_GAMESTATE = "CHANGE_GAMESTATE";
//PROJECTILE
export const CREATE_PROJECTILE = "CREATE_PROJECTILE";
export const UPDATE_PROJECTILE_LOCATION = "UPDATE_PROJECTILE_LOCATION";
export const NULL_PROJECTILE = "NULL_PROJECTILE";
//PLAYER
export const UPDATE_PLAYER_HEALTH = "UPDATE_PLAYER_HEALTH";
export const UPDATE_PLAYER_LOCATION = "UPDATE_PLAYER_LOCATION";
export const UPDATE_PLAYER_DIRECTION = "UPDATE_PLAYER_DIRECTION";
//ENEMY
export const CREATE_ENEMY = "CREATE_ENEMY";
export const UPDATE_ENEMY_LOCATION = "UPDATE_ENEMY_LOCATION";
export const UPDATE_ENEMY_DIRECTION = "UPDATE_ENEMY_DIRECTION";
export const UPDATE_ENEMY_HEALTH = "UPDATE_ENEMY_HEALTH";
export const NULL_ENEMY = "NULL_ENEMY"
